// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCU9NSbPHN34hIKXrZelW41yYxPVSJw8',
    appId: '1:745934588420:web:56a386071b212535988351',
    messagingSenderId: '745934588420',
    projectId: 'nouvelle-a9646',
    authDomain: 'nouvelle-a9646.firebaseapp.com',
    storageBucket: 'nouvelle-a9646.appspot.com',
    measurementId: 'G-MKWM3J3DRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCPVgNxvs3wvFZAzYFR75PDsBp4VuNr-Q',
    appId: '1:745934588420:android:163cbc7f7b61873c988351',
    messagingSenderId: '745934588420',
    projectId: 'nouvelle-a9646',
    storageBucket: 'nouvelle-a9646.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdKWM0HIHsj0-QcFOS9aHuTWqTZe2Ot6k',
    appId: '1:745934588420:ios:9dd651cdfe0e94aa988351',
    messagingSenderId: '745934588420',
    projectId: 'nouvelle-a9646',
    storageBucket: 'nouvelle-a9646.appspot.com',
    iosClientId:
        '745934588420-jmgnrmp2a2opcuqi5q1ooq7olt58t6ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.nouvelle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdKWM0HIHsj0-QcFOS9aHuTWqTZe2Ot6k',
    appId: '1:745934588420:ios:9dd651cdfe0e94aa988351',
    messagingSenderId: '745934588420',
    projectId: 'nouvelle-a9646',
    storageBucket: 'nouvelle-a9646.appspot.com',
    iosClientId:
        '745934588420-jmgnrmp2a2opcuqi5q1ooq7olt58t6ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.nouvelle',
  );
}
